services:
- type: web
  name: waveform-plotter-backend
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --bind 0.0.0.0:$PORT app:app
  envVars:
    - key: SECRET_KEY
      value: your_super_secret_key_from_render_dashboard