services:
- type: web
  name: lissajous-patterns-generator
  env: python
  plan: free
  buildCommand: pip install -r requirements.txt
  startCommand: gunicorn --worker-class geventwebsocket.gunicorn.workers.GeventWebSocketWorker --bind 0.0.0.0:$PORT app:app
  envVars:
    - key: SECRET_KEY
      value: your_new_secret_key_for_lissajous